# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: Home
    url: /
  archives:
    text: Archive
    url: /archives
  tags:
    text: Tags
    url: /tags
  user:
    text: About
    url: /about
  github-alt:
    text: Github
    url: https://github.com/ivitan
    target: _blank

# 你的头像url
avatar: /img/ivitan.png
# avatar link
avatar_link: /
# 头像背景图
brand: /img/brand.png
# favicon
favicon: /img/favicon.png

# email
email: admin@vitan.me

# 设置 Android L Chrome 浏览器状态栏颜色
color: "#f45a8d"

# 页面标题
tags_title: Tags
archives_title: Archives
categories_title: Categories

# 文章截断
excerpt_render: true
excerpt_length: 300
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: false

# 是否开启打赏，关闭 reward: false
reward:
  title: 感谢支持
  wechat: /img/wechat.png #微信，关闭设为 false
  alipay: /img/alipay.png #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启toc
# toc: false
toc:
  list_number: true # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 本文链接：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: UA-144334903-1
google_adsense: false
google_site_verification: false

# sogou站长验证 http://zhanzhang.sogou.com/
sogou_site_verification: ivC590WMZh

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
# gitment:
#   owner:
#   repo:
#   client_id:
#   client_secret:

# use gitalk://github.com/gitalk/gitalk
gitalk: false
#  owner:
#  repo:
#  client_id:
#  client_secret:

# Valine Comment system. https://valine.js.org
valine:
  enable: ture
  appId: D33WPBHpBw2CjwdWpFvpUhDm-MdYXbMMI
  appKey: MzQtKvSeVPU4nS4ljd3zlbMp
  notify: ture # Mail notify
  verify: false # Verify code
  avatar: wavatar # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Write a comment here. # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# 是否开启Hyper Comments，填写id则启用，false则禁用。http://hypercomments.com
# Hyper Comments support. Write your id here, or false to disable
hyper_id: false

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
canonical: https://vitan.me

# 版权起始年份
since_year: 2017

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: false

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: <i class="icon icon-user"></i>
  site_pv: <i class="icon icon-eye"></i> 

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: false